"""empty message

Revision ID: b4038c30b6a5
Revises: ddbcc1ca9925
Create Date: 2020-11-22 18:06:34.729041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4038c30b6a5'
down_revision = 'ddbcc1ca9925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('compiled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'compiled')
    # ### end Alembic commands ###
